
backend:
  name: git-gateway
  branch: main
  commit_messages:
    create: "Create {{collection}} "{{slug}}""
    update: "Update {{collection}} "{{slug}}""
    delete: "Delete {{collection}} "{{slug}}""
    uploadMedia: "[skip ci] Upload "{{path}}""
    deleteMedia: "[skip ci] Delete "{{path}}""

local_backend: true
media_folder: "public/images/uploads"
public_folder: "/images/uploads"
publish_mode: editorial_workflow

collections:
  - name: "products"
    label: "Products"
    folder: "content/products"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "ID", name: "id", widget: "string" }
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Price", name: "price", widget: "number", value_type: "float" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Category", name: "category", widget: "string" }
      - {
          label: "Ingredients",
          name: "ingredients",
          widget: "list",
          field: { label: "Ingredient", name: "ingredient", widget: "string" },
        }
